# SITE CONFIGURATION
title: "" # your site title
author: "" # You :P
description: > # Meta description of Homepage
  Hello, I'm Fadil. 
  I'm a Master's CS student at the Johns Hopkins University. This is my blog. 
  I'm planning to post projects that I've undertaken along with tutorial-like documentation here. 
  I'm always eager to connect, so if you'd like to discuss projects, share ideas, or simply say hello,
  feel free to reach out! Connect with me on LinkedIn and GitHub (links in the footer), or send me an email through the "Contact" section.
baseurl: "" # My base url: Must match my repo name.
url: "https://Fadil-1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year/:month/:day/:title/ # Structures projects in _posts so that they can be placed into sub directories.


github: https://github.com/Fadil-1 
linkedin: https://www.linkedin.com/in/fadil-isamotu-b2b0241a1/

favicon: 376843.png
# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Customize on line 29 under the config.yml file

hero_img: home_img.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/1688123497021.jpg


# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
